bounding_box:
  - - 128.50011587536375
    - -26.499911390797962
  - - 138.50018768629417
    - -10.468357028999876
capacity:
  biomass: 1.1
  gas: 471.4
  solar: 158
contributors:
  - unitrium
  - amv213
country: AU
delays:
  consumption: 30
  price: 30
  production: 55
disclaimer: The Northern Territory power grid is not connected to the (Australian)
  National Electricity Market or Western Australia's grid.
parsers:
  consumption: NTESMO.fetch_consumption
  price: NTESMO.fetch_price
  production: NTESMO.fetch_production
region: Oceania
timezone: Australia/Darwin
