bounding_box:
  - - -74.5185401854018
    - -34.24045114057622
  - - -34.29614796147959
    - 5.766573637368978
capacity:
  hydro: 109413
  nuclear: 1990
  solar: 30431
  unknown: 39584
  wind: 25628
contributors:
  - alexanmtz
  - corradio
  - systemcatch
  - nessie2013
  - VIKTORVAV99
estimation_method: RECONSTRUCT_BREAKDOWN
subZoneNames:
  - BR-CS
  - BR-N
  - BR-NE
  - BR-S
region: Americas
country: BR
