bounding_box:
  - - -139.56020662181913
    - 47.80609772300011
  - - -113.53745235883926
    - 60.50005890629359
capacity:
  biomass: 838
  gas: 507
  hydro: 15898
  solar: 1
  wind: 704
contributors:
  - daveachuk
emissionFactors:
  lifecycle:
    unknown:
      - datetime: '2019-01-01'
        source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
        value: 56
  direct:
    unknown:
      - datetime: '2019-01-01'
        source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
        value: 28.6
isLowCarbon:
  unknown:
    - datetime: '2019-01-01'
      source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
      value: 0.94
isRenewable:
  unknown:
    - datetime: '2019-01-01'
      source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
      value: 0.94
fallbackZoneMixes:
  _source: List of Generating Stations in BC (Wikipedia)
  _url: https://en.wikipedia.org/wiki/List_of_generating_stations_in_British_Columbia
  powerOriginRatios:
    value:
      biomass: 0.09
      gas: 0.01
      hydro: 0.88
      unknown: 0.01
      wind: 0.01
parsers:
  consumption: CA_BC.fetch_consumption
timezone: America/Vancouver
region: Americas
country: CA
