aggregates_displayed:
  - daily
  - monthly
  - yearly
bounding_box:
  - - -110.49997270417693
    - 48.49261789994816
  - - -100.86433964677866
    - 60.50005890629359
capacity:
  coal:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 1389
  gas:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 2065
  hydro:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 865
  solar:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 93
  unknown:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 324
  wind:
    - datetime: '2024-01-01'
      source: saskpower.com
      value: 617
contributors:
  - VIKTORVAV99
country: CA
delays:
  production: 48
disclaimer: The hourly production mix is estimated based on the daily average production
  mix.
parsers:
  consumption: CA_SK.fetch_consumption
  production: CA_SK.fetch_production
region: Americas
timezone: America/Regina
