bounding_box:
  - - -3.470256683510813
    - 34.76572463778479
  - - -2.426766941365234
    - 35.8209422034335
capacity:
  biomass:
    - datetime: '2022-12-01'
      source: ree.es
      value: 1.0
  gas:
    - datetime: '2022-12-01'
      source: ree.es
      value: 12.0
  oil:
    - datetime: '2022-12-01'
      source: ree.es
      value: 64.0
  solar:
    - datetime: '2022-12-01'
      source: ree.es
      value: 0.0
  unknown:
    - datetime: '2022-12-01'
      source: ree.es
      value: 1.0
contributors:
  - VIKTORVAV99
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
  productionCapacity: REE.fetch_production_capacity
timezone: Europe/Madrid
region: Europe
country: ES
