bounding_box:
  - - -54.708003
    - 2.10212
  - - -51.595232
    - 5.78601
capacity:
  biomass:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 5.0
  coal:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  gas:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  geothermal:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  hydro:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 119.0
  hydro storage:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  nuclear:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  oil:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 197.0
  solar:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 55.0
  unknown:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  wind:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
contributors:
  - PETILLON-Sebastien
  - VIKTORVAV99
parsers:
  price: FR_O.fetch_price
  production: FR_O.fetch_production
  productionCapacity: IRENA.fetch_production_capacity
timezone: Europe/Paris
region: Americas
country: GF
