bounding_box:
  - - 73.740234
    - 17.936929
  - - 106.633301
    - 33.486435
capacity:
  biomass: 15.8
  coal: 750.0
  gas: 1664.95
  hydro: 2322.21
  nuclear: 0
  oil: 36
  solar: 202.99
  unknown: 0
  wind: 0
contributors:
  - unitrium
country: IN
delays:
  production: 75
parsers:
  consumption: IN.fetch_consumption
  production: IN.fetch_production
region: Asia
timezone: Asia/Kolkata
