bounding_box:
  - - 135.84
    - 33.82
  - - 138.72
    - 37.17
capacity:
  biomass: 352.6
  coal: 5170
  gas: 14136
  geothermal: 2
  hydro: 2180
  hydro storage: 3320
  nuclear: 3617
  oil: 2275
  solar: 550
  wind: 210
contributors:
  - tmslaine
  - lorrieq
  - pierresegonne
  - wobniarin
country: JP
delays:
  production: 5
disclaimer: The data provided for solar power production is suspected to be too high
  (source; Chubu Electric Power Co.,Inc.).
emissionFactors:
  lifecycle:
    unknown:
      _comment: 'Source: Derived from 2016-2019 Chubu area supply statistics and 2017-2018
        Chubu Electric report'
      _url:
        - https://www.chuden.co.jp/corporate/publicity/datalist/juyo/dat_kousei/index.html
        - http://denki-yoho.chuden.jp/denki_yoho_content_data/areabalance_current_term.csv
      source: assumes 26.3% coal, 2.2% oil, 62.5% gas, 9% hydro and wind
      value: 538
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
region: Asia
timezone: Asia/Tokyo
