bounding_box:
  - - 135.8
    - 35.39
  - - 137.75
    - 37.9
capacity:
  biomass: 700
  coal: 2900
  gas: 1194.7
  geothermal: 0
  hydro: 1934
  nuclear: 1746
  oil: 1750
  wind: 229.6
contributors:
  - tmslaine
  - lorrieq
  - pierresegonne
  - wobniarin
  - PPsyrius
country: JP
delays:
  production: 5
disclaimer: The data provider (Hokuriku Electric Power Co.,Inc.) provides live data
  only for solar and unknown. We are working on improving the data quality for this
  zone.
emissionFactors:
  lifecycle:
    unknown:
      source: Enerdata 2022 Japanese National Average
      value: 462
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
region: Asia
sources:
  Enerdata 2022 Japanese National Average:
    link: https://www.climate-transparency.org/wp-content/uploads/2022/10/CT2022-Japan-Web.pdf
timezone: Asia/Tokyo
