bounding_box:
  - - 137.65
    - 36.65
  - - 142
    - 41.66
capacity:
  biomass: 600
  coal: 6200
  gas: 7000
  geothermal: 188.8
  hydro: 2000
  hydro storage: 460
  nuclear: 2750
  oil: 2500
  solar: 7000
  unknown: 0
  wind: 1800
contributors:
  - tmslaine
  - lorrieq
  - PPsyrius
  - mathilde-daugy
country: JP
delays:
  production: 5
emissionFactors:
  lifecycle:
    unknown:
      source: Enerdata 2022 Japanese National Average
      value: 462
parsers:
  consumptionForecast: JP.fetch_consumption_forecast
  price: JP.fetch_price
  production: JP.fetch_production
region: Asia
sources:
  Enerdata 2022 Japanese National Average:
    link: https://www.climate-transparency.org/wp-content/uploads/2022/10/CT2022-Japan-Web.pdf
timezone: Asia/Tokyo
