bounding_box:
  - - 81.37741877418776
    - 6.592635332223807
  - - 82.37741877418776
    - 7.592635332223807
capacity:
  biomass:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 45.0
  coal:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 900.0
  gas:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  geothermal:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  hydro:
    - datetime: '2022-01-01'
      source: IRENA.org
      value: 1846.0
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 1799.0
  hydro storage:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  nuclear:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 0.0
  oil:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 1087.0
  solar:
    - datetime: '2022-01-01'
      source: IRENA.org
      value: 714.0
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 624.0
  unknown:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 5.0
  wind:
    - datetime: '2021-01-01'
      source: IRENA.org
      value: 252.0
contributors:
  - q--
country: LK
delays:
  production: 30
parsers:
  production: CEB.fetch_production
  productionCapacity: IRENA.fetch_production_capacity
region: Asia
timezone: Asia/Colombo
