aggregates_displayed:
  - none # We are not showing this zone due to lack of data
bounding_box:
  - - -118.86880422899992
    - 22.37215511800008
  - - -108.91362465499992
    - 33.21283640500009
parsers:
  consumption: CENACE.fetch_consumption
timezone: America/Tijuana
region: Americas
country: MX
