bounding_box:
  - - 2.1710819900001184
    - 3.7721621770000695
  - - 15.16993615700008
    - 14.380290832000114
capacity:
  biomass:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 20.0
  coal:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 280.0
  gas:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 11290.0
  hydro:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 2110.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 2850.0
  solar:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 70.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 110.0
contributors:
  - byronwilliams
  - kruschk
  - nessie2013
  - silimotion
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 280.82249604736285
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 280.82249604736285
  lifecycle:
    battery discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 377.6844057534393
    hydro discharge:
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 377.6844057534393
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.7589794653377564
        geothermal: 0.0
        hydro: 0.24102053466224352
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.0
parsers:
  production: NG.fetch_production
  productionCapacity: EMBER.fetch_production_capacity
timezone: Africa/Lagos
region: Africa
country: NG
