bounding_box:
  - - 116.46336963369632
    - 7.323918659865512
  - - 124.9190441904419
    - 19.14290487703049
capacity:
  battery storage: 72
  biomass: 175
  coal: 8792
  gas: 3731
  hydro: 1806
  hydro storage: 736
  nuclear: 0
  oil: 2357
  solar: 960
  wind: 337
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
country: PH
delays:
  production: 25
parsers:
  production: IEMOP.fetch_production
region: Asia
timezone: Asia/Manila
