bounding_box:
  - - 119.31099810998111
    - 4.57480853775256
  - - 127.08266582665826
    - 10.957111072508837
capacity:
  battery storage: 49
  biomass: 79
  coal: 2268
  gas: 0
  hydro: 1191
  nuclear: 0
  oil: 833
  solar: 84
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
country: PH
delays:
  production: 25
parsers:
  production: IEMOP.fetch_production
region: Asia
timezone: Asia/Manila
