bounding_box:
  - - 121.35221852218521
    - 8.534614736548264
  - - 126.21145711457112
    - 13.07797583095308
capacity:
  battery storage: 35
  biomass: 326
  coal: 1412
  gas: 1
  hydro: 36
  nuclear: 0
  oil: 644
  solar: 487
  wind: 90
contributors:
  - VIKTORVAV99
  - jarek
  - systemcatch
  - q--
  - mathilde-daugy
  - pierresegonne
  - xomanuel
country: PH
delays:
  production: 25
parsers:
  production: IEMOP.fetch_production
region: Asia
timezone: Asia/Manila
