bounding_box:
  - - -107.862115248933
    - 28.4286900252724
  - - -81.9130970652477
    - 49.884274119856
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 82.0
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 81.5
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2285.1
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 2282.4
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 2281.8
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 50924.4
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 50159.1
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 50124.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 83093.1
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 82979.7
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 82306.0
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2456.9
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 2452.9
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 2451.3
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2416.8
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 12269.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 4108.2
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 4128.3
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 4100.3
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 5665.8
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 7191.8
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 7364.8
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 487.5
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 512.8
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 30866.3
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 31239.7
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 31237.2
comment: Midcontinent Independent Transmission System Operator, Inc..
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 34
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 410.59276844184876
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 535.1368239693278
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 525.6208427815583
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 599.7945813485389
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 515.2704076576499
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 459.620851356594
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 501.3722920933296
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1013.675084
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 1003.7
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 409.253592
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 409.43
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 410.59276844184876
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 535.1368239693278
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 525.6208427815583
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 599.7945813485389
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 515.2704076576499
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 459.620851356594
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 501.3722920933296
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 922.7890878
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 613.58
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 483.0838833413798
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 608.5565899808616
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 598.1259264670572
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 669.158297048614
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 581.1804536398149
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 525.7339513345104
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.6209396789254
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 139.1151962
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1076.354463
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1066.379379
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 529.253592
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 529.4300000000001
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 483.0838833413798
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 608.5565899808616
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 598.1259264670572
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 669.158297048614
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 581.1804536398149
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 525.7339513345104
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.6209396789254
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 1166.7890877999998
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 857.58
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.45
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3645360263350062
        gas: 0.3003757973698458
        geothermal: 0.0
        hydro: 0.016948056758411878
        hydro discharge: 0.0
        nuclear: 0.15206559969645714
        oil: 0.03924092846577229
        solar: 0.0026028591830364245
        unknown: 0.01126095447154677
        wind: 0.11296972871934247
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3645360852974365
        gas: 0.30037584595458294
        geothermal: 0.0
        hydro: 0.01694805949970092
        hydro discharge: 0.0
        nuclear: 0.15206562429253728
        oil: 0.039240934812855545
        solar: 0.0026026978505841476
        unknown: 0.011260956292966863
        wind: 0.11296974699180189
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
  productionPerModeForecast: US_MISO.fetch_wind_forecast
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Central
