bounding_box:
  - - -74.22789
    - 40.10968
  - - -66.45013
    - 47.9598300000001
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 332.3
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 368.2
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1281.3
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 1247.5
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 459.2
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 18600.2
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 18599.1
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 18618.4
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1905.9
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 1903.9
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 1897.9
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1499.0
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 1532.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3404.9
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 3501.9
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 5886.3
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 5861.3
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 5867.9
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2394.8
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 2590.3
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 2804.2
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1538.2
comment: Iso New England Inc.
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 225.5945374112616
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 246.90134260343558
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 246.9012476919782
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 206.8950363063045
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 178.95087048701706
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 186.1560490413342
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 196.32177755564254
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1042.155724
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 1049.54
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 389.0568749
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 388.41
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 225.5945374112616
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 246.90134260343558
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 246.9012476919782
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 206.8950363063045
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 178.95087048701706
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 186.1560490413342
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 196.32177755564254
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1257.197843
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 781.56
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 313.0342866311471
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 345.4491038288679
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 345.4489816005894
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 296.52148231192876
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 259.83501257693626
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 270.84303116673414
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 283.25905267667025
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 429.7692167
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1133.712784
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1141.09706
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 509.0568749
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 508.41
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 313.0342866311471
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 345.4491038288679
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 345.4489816005894
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 296.52148231192876
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 259.83501257693626
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 270.84303116673414
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 283.25905267667025
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 1501.197843
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 1025.56
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.825
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.00048084385739457066
        biomass: 0.054681157499140355
        coal: 0.007996509728253222
        gas: 0.4908440982677455
        geothermal: 0.0
        hydro: 0.06949196441962709
        hydro discharge: 0.0
        nuclear: 0.26945112839727786
        oil: 0.01139241061681868
        solar: 0.004028317739736292
        unknown: 0.05769620577852697
        wind: 0.03393717612619065
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0004808440431203622
        biomass: 0.05468117861972057
        coal: 0.007996512816902638
        gas: 0.49084428785612705
        geothermal: 0.0
        hydro: 0.06949199126087692
        hydro discharge: 0.0
        nuclear: 0.2694512324726931
        oil: 0.01139241501713377
        solar: 0.004027933082009133
        unknown: 0.05769622806366866
        wind: 0.03393718923441447
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.00048084385739457066
        biomass: 0.054681157499140355
        coal: 0.007996509728253222
        gas: 0.4908440982677455
        geothermal: 0.0
        hydro: 0.06949196441962709
        hydro discharge: 0.0
        nuclear: 0.26945112839727786
        oil: 0.01139241061681868
        solar: 0.004028317739736292
        unknown: 0.05769620577852697
        wind: 0.03393717612619065
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0005776128212160682
        biomass: 0.05080329375207368
        coal: 0.010283679198102146
        gas: 0.4725490157578836
        geothermal: 2.009264166294219e-06
        hydro: 0.1741549416336133
        hydro discharge: 3.8980778131073676e-07
        nuclear: 0.24573185179041473
        oil: 0.001978405049001384
        solar: 0.004609380857449354
        unknown: 0.0006535612908342227
        wind: 0.03869001278558905
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: US_NEISO.fetch_production
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
