bounding_box:
  - - -124.00616
    - 45.8837600000001
  - - -120.56592
    - 48.28046
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 64.0
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 0.0
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 716.6
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: City Of Tacoma, Department Of Public Utilities, Light Division
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 32
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 0.0
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 0.0
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 0.0
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 52.27932116142599
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 68.97211542140349
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.99484981291907
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 36.76361635161157
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 0.0
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 0.0
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 0.0
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 52.27932116142599
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 68.97211542140349
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.99484981291907
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 36.76361635161157
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.0
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.000000000000004
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 24.0
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 82.08834886036942
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 98.65832385772822
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 53.05324909707979
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 64.29134040496706
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 25.02597585
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 816.445393
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.0
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.000000000000004
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 24.0
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 82.08834886036942
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 98.65832385772822
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 53.05324909707979
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 64.29134040496706
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 1.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 1.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 1.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.0
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Pacific
