bounding_box:
  - - -125.23688
    - 39.61659
  - - -105.50971
    - 49.50244
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 32.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 303.4
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 293.6
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 729.9
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2271.7
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 2167.0
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 18.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 19577.9
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 19737.6
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 19752.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 314.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1200.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 137.9
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3617.1
comment: Bonneville Power Administration
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 32
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available. This zone includes all wind related electricity production
  from the generation-only balancing authority Avangrid Renewables, LLC. Read more
  on the zone definition wiki page.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 35.80752038343632
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 37.46689709875655
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 37.42638983296459
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 74.41631978617512
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 89.58457817802649
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 42.135777033410335
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 64.16281498516693
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1134.898924
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 1118.44
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 394.4247594
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 385.5
    geothermal:
      datetime: '2020-01-01'
      source: eGrid 2020
      value: 0.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 35.80752038343632
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 37.46689709875655
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 37.42638983296459
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 74.41631978617512
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 89.58457817802649
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 42.135777033410335
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 64.16281498516693
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 66.0758425413272
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 67.71636960293682
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 67.67167508149652
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 106.92282388806439
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 121.28467682490931
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 70.82164514895452
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 94.64933322719386
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 85.91723542
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 1194.898924
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 1178.44
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 514.4247594000001
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 505.5
    geothermal:
      datetime: '2020-01-01'
      source: eGrid 2020; IPCC 2014
      value: 38.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 66.0758425413272
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 67.71636960293682
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 67.67167508149652
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 106.92282388806439
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 121.28467682490931
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 70.82164514895452
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 94.64933322719386
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 32.8
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.06791398932896388
        geothermal: 0.0
        hydro: 0.7382562221049005
        hydro discharge: 0.0
        nuclear: 0.10063685899286395
        oil: 0.0
        solar: 0.001463661054655146
        unknown: 0.018573904640700974
        wind: 0.07315532407706106
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.06791400826213059
        geothermal: 0.0
        hydro: 0.738256427917109
        hydro discharge: 0.0
        nuclear: 0.10063688704856275
        oil: 0.0
        solar: 0.0014633826811540872
        unknown: 0.018573909818762762
        wind: 0.07315534447141515
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 6.826404758671036e-08
        biomass: 3.2464208994361687e-07
        coal: 6.249780417313596e-06
        gas: 0.06783483299171798
        geothermal: 6.465691325400351e-07
        hydro: 0.7387561594236416
        hydro discharge: 2.075071901073298e-07
        nuclear: 0.10042080216300388
        oil: 5.998961757620001e-08
        solar: 0.0015106497582219824
        unknown: 0.01854558147361244
        wind: 0.0729243836931472
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Pacific
